language: node_js
node_js:
- '10'
- '11'
- '12'
- '13'
- '14'
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
before_script:
- "./cc-test-reporter before-build"
script: npm run-script test-cov
after_success:
- test -e ./.coverage/lcov.info && ./cc-test-reporter format-coverage -t lcov ./.coverage/lcov.info
  && ./cc-test-reporter upload-coverage
notifications:
  email:
  - snowyu.lee@gmail.com
env:
  global:
    secure: fkbl17HhirT0graAVeqErg2zdzGsxha91rbBYoJ6w415+kFydJ4JbAULtS2x0MrOHycFBqxsOt2VReSz/JDhR3ao2PaXaSwD4omQoUP6MbWAg0WPfVaYkB+cHnxxc018jZh/TpzukA9FLSEgy+XTE39pwwWZEAm/7dAb+oXIWmhJRsMZ54VrQFPVq2ExPNuSeMV42ltUk3HWqHqCNciN8gR2MUUet1lBoyl7Wh7rOlcpyqjg7/RDyPsko6dGpA+mSLCavyIN/emlOOAp8FEN+AAghefjR3xvpvYyBnhkVuAOn5sfJoDu+k+BLAF8yudXa8IRurTgkCcfqL5DbTeKds2EokVdPi188dRqJ9NsvD8WaYQ4Th1p71QoRdWGzn2zoYkXFX5ESU0TqdpE4BILYLB4QeFzlYZInvVdfBUXKNFXDRuzXFhk6wph8bMjfBiEGSS9Y+CSHtvsFR9yW+2N4q1/UtlqJgDsctgNwBbn4bARrQgWM3ibIR29yF3vnb4Gs+aur2HMwDrPZCxUVg+kUruavpQ7XBTwfivV/nTs1eF5Shfq6QUuWKVpp1ZmXNOy4LL9kXlc6IDfgWaMdcowZPUNDQ/T6NKNZ6VKX5sQWgaHnK2xgtfr/gSkG7JgGB4gl/sg1oWyymmWSqZEEYG1TCjllUUd4+1S0TtDANzLlJE=
